### PR TITLE
Made sure rebasing is truly aborted when negative z-index found

### PR DESCRIPTION
**Pull request by niccai**
If a negative z-index isn’t the first z-index value found, all z-index values
remain unchanged. Previously, positive z-indexes occurring prior to the negative z-index would be rebased causing a broken stacking context.

Also, I added a warning if rebasing is aborted.

### CODE REVIEW

**Comment by ben-eb** [comment]
Thanks for your contribution. :+1: 

Is the warning necessary? I think if we should notify, we should use messages instead (https://github.com/postcss/postcss/blob/master/docs/api.md#resultmessages), and, there should be a unit test for this also.

/cc @TrySound Any thoughts on messages?

**Comment by TrySound** [comment]
I don't think we should inform about aborting. It's use case for linter. Minifier should minify or ignore caz it's not its responsibility.

**Comment by ben-eb** [comment]
I think that whilst we are not a linter we could still inform users of operations that were performed. A good example of this use case is https://github.com/ben-eb/postcss-discard-empty/pull/9#issuecomment-204374816 - it makes debugging easier too.

**Comment by niccai** [comment]
Up to you anout removing it. I'm really not 100% sure of the best way to inform the user inside a postcss plugin, but I will say that I spent several hours tracking this issue down.  Some sort of console message would have helped a lot. Personally, I'd also like to know that it was aborted - even if it hadn't created an issue for me.  Up to you. Thanks!

**Comment by ben-eb** [comment]
I think I'm going to revisit logging for v4. Merged this in https://github.com/ben-eb/postcss-zindex/commit/bd7826ece29cdb2f2550d343e4cc93aaa5e089d6 & published 2.1.1.

**Pull request closed without merging**
